### ISSUE TITLE
Live Streaming Support

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#814]
In the past the Support for Opencast livestreams in the plugin was sketchy at best. The goal of this enhancement is, to have a fully working integration, even making changes in Opencast itself if necessary, this includes:
- [ ] Planning of livestreams from Stud.IP (see also #330)
- [ ] Listing planned livestreams without breaking anything in Opencast (see #367, #353)
- [ ] Seamless integration into the UI
- [ ] Put recorded Livestreams in a separate playlist, if user wants to ( #505 )

**Comment by tgloeggl** [comment]
Integration idea:
- [ ] Widget on Stud.IPs start page with a list of my upcoming livestreams, be it as a consumer or a creator 
- [ ] Show upcoming livestreams in the course playlist - these entries will become the recorded videos after the live stream is done and the video has been processed.
- [ ] Allow users to configure, which playlist is used for scheduled videos -> can be configured on the scheduling page

**Comment by tgloeggl** [comment]
# Allow users to configure, which playlist is used for scheduled videos -> can be configured on the scheduling page

![playlist_for_recordings](https://github.com/elan-ev/studip-opencast-plugin/assets/6160/90fd5623-90b2-455d-9443-7d97df4e1fc5)

**Comment by tgloeggl** [comment]
Bulk operations on "Schedule recoding" page

![bulk_operations](https://github.com/elan-ev/studip-opencast-plugin/assets/6160/052216a9-bae5-4609-9f3d-a97c253a4dad)

**Comment by tgloeggl** [comment]
# Show upcoming livestreams in the course playlist - these entries will become the recorded videos after the live stream is done and the video has been processed.

![live_video_in_list](https://github.com/elan-ev/studip-opencast-plugin/assets/6160/d2cb2152-bb0e-4778-aa67-19a2fa8a917e)

**Comment by tgloeggl** [comment]
# Widget on Stud.IPs start page with a list of my upcoming livestreams, be it as a consumer or a creator

![startpage_widget](https://github.com/elan-ev/studip-opencast-plugin/assets/6160/f678db66-eb56-47a4-9305-3d754d82122a)

- [ ] A click on the link "Test Lehrveranstaltung" redirects to the playlist in the course, where the live event is listed.

**Comment by ferishili** [comment]
The implemented concept is now:
- When configuring Resources in SOP admin setting; it is required for livestream capability to set an specific workflow that can handle livestreaming (namely: publichLive=true)
- If this workflow is not set for each capture agent, it is considered for the feature to be deactivated.

### Help to create the livestream workflow:
In order to make a workflow ready for livestream, we have to add `publishLive` set as `true` configuration parameter to its default config-params. like the following:
```
...
 <operations>
...
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- Apply default workflow properties                                 -->
    <!--                                                                   -->
    <!-- The worklfow properties are simplified for a better               -->
    <!-- user experience, please preconfigure your defaults here.          -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <operation
      id="defaults"
      description="Applying default configuration values">
      <configurations>
        ...
        <configuration key="publishLive">true</configuration>
      </configurations>
    </operation>
...
 </operations>
```

#### Example
Usually the `schedule-and-upload` workflow is also used to schedule a live-event, therefore, the following worklfow is an extended version of that workflow:
(the default workflow is taken from: [schedule-and-upload.xml](https://github.com/opencast/opencast/blob/develop/etc/workflows/schedule-and-upload.xml))

```
<?xml version="1.0" encoding="UTF-8" ?>
<definition xmlns="http://workflow.opencastproject.org">

  <id>schedule-and-upload-with-publish-live</id>
  <title>Process upon upload and schedule with publish live</title>
  <tags>
    <tag>upload</tag>
    <tag>schedule</tag>
  </tags>
  <displayOrder>1000</displayOrder>
  <description>
    The default workflow for processing media.

    If straight to publishing is checked, then the uploaded media will be published without cutting.
  </description>
  <configuration_panel>
    <![CDATA[
      <div id="workflow-configuration">
        <fieldset>
          <input id="straightToPublishing" name="straightToPublishing" type="checkbox" class="configField" value="true" />
          <label for="straightToPublishing">Straight to publishing</label>
        </fieldset>
      </div>
    ]]>
  </configuration_panel>
  <configuration_panel_json>
    [{
      "fieldset": [
        {
          "type": "checkbox",
          "name": "straightToPublishing",
          "label": "Straight to publishing",
          "value": true
        }
      ]
    }]
  </configuration_panel_json>
  <operations>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- Apply default workflow properties                                 -->
    <!--                                                                   -->
    <!-- The worklfow properties are simplified for a better               -->
    <!-- user experience, please preconfigure your defaults here.          -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <operation
      id="defaults"
      description="Applying default configuration values">
      <configurations>
        <configuration key="straightToPublishing">true</configuration>
        <configuration key="publishLive">true</configuration>
      </configurations>
    </operation>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- Prepare asset                                                     -->
    <!--                                                                   -->
    <!-- Prepare the recording for asset management, including creation of -->
    <!-- previews, audio waveforms and storing of the recording data in    -->
    <!-- the asset area for further processing.                            -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <!-- Make sure all elements are downloaded from external sources and   -->
    <!-- inside of Opencast                                                -->

    <operation
      id="include"
      description="Finalize upload and ingest">
      <configurations>
        <configuration key="workflow-id">partial-ingest</configuration>
      </configurations>
    </operation>

    <!-- Archive the source material -->

    <operation
      id="snapshot"
      description="Archive raw recording after ingest">
      <configurations>
        <configuration key="source-tags">archive</configuration>
      </configurations>
    </operation>

    <!-- Create preview artifacts -->

    <operation
      id="include"
      description="Prepare preview versions of the recording">
      <configurations>
        <configuration key="workflow-id">partial-preview</configuration>
      </configurations>
    </operation>

    <!-- Archive generated preview assets -->

    <operation
      id="snapshot"
      description="Archive preview information">
      <configurations>
        <configuration key="source-tags">archive</configuration>
      </configurations>
    </operation>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- Tag for review and cutting                                        -->
    <!--                                                                   -->
    <!-- Add comments in order to mark the recording for preview and/or    -->
    <!-- cutting.                                                          -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <!-- Mark the recording for cutting -->

    <operation
      id="comment"
      if="NOT ${straightToPublishing}"
      description="Mark the recording for cutting">
      <configurations>
        <configuration key="description">Recording has not been cut yet.</configuration>
        <configuration key="reason">EVENTS.EVENTS.DETAILS.COMMENTS.REASONS.CUTTING</configuration>
        <configuration key="action">create</configuration>
      </configurations>
    </operation>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- Publish                                                           -->
    <!--                                                                   -->
    <!-- Encode and publish the recording to the predefined                -->
    <!-- publication channels.                                             -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <operation
      id="include"
      if="${straightToPublishing}"
      description="Publish the recording">
      <configurations>
        <configuration key="workflow-id">partial-publish</configuration>
      </configurations>
    </operation>

    <!-- Archive the recording -->

    <operation
      id="snapshot"
      if="${straightToPublishing}"
      description="Archive publishing information">
      <configurations>
        <configuration key="source-tags">archive</configuration>
      </configurations>
    </operation>

    <!-- Clean up work artifacts -->

    <operation
      id="cleanup"
      fail-on-error="false"
      description="Remove temporary processing artifacts">
      <configurations>
        <!-- On systems with shared workspace or working file repository -->
        <!-- you want to set this option to false. -->
        <configuration key="delete-external">true</configuration>
        <!-- ACLs are required again when working through ActiveMQ messages -->
        <configuration key="preserve-flavors">security/*</configuration>
      </configurations>
    </operation>

  </operations>
</definition>
```

**Comment by kai-wng-uos** [comment]
Scheduling currently doesnt work on any of our test systems, we can therefor not test this.
